import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
 
const openSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans} overflow-x-hidden flex flex-col text-[#e1e0e0] bg-[#000000] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
